### ISSUE TITLE
footer tab bar hides the top header title

### ISSUE THREAD

**Issue by db2277** [tapquo/Lungo.js#58]
when you create a simple tab bar app, and you move from tab to tab, it hides the top section header (even though data-title is not empty in the links), and makes an ugly space under the tab bar.

**Comment by soyjavi** [comment]
Show me the code :)

**Comment by soyjavi** [comment]
The order in a section is

section
   header..
   footer...
   aside...

   article...
   article...
/section

**Comment by db2277** [comment]
Hi Javier
thanks for the reply.
I really like the concept of LungoJS since its lightweight and cool (and i
tried ALL frameworks).
I changed to the order you wrote, but still same issue:
Look: http://rvmon.lotemx.net/lungojs/index.html
Thanks man
Dan

2012/1/22 Javier Jimnez <
reply@reply.github.com

> The order in a section is
> 
> <section>
>   <header>...
>   <footer>...
>   <aside>...
> 
>   <article>...
>   <article>...
> </section>
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3601739

## 

Best regards,

_Dan Berachowitz, CEO_
Lotem Group ltd.

Office: +972 (77) 8866789
Mobile: +972 (52) 2269978

Hebrew: www.lotemx.com
English: www.lotemx.net

**Comment by soyjavi** [comment]
What versin of mobile?
El 22/01/2012 09:17, "db2277" <
reply@reply.github.com>
escribi:

**Comment by db2277** [comment]
Iphone 4 version 4 or something.  Not ios5.
בתאריך 2012 1 22 11:50, מאת "Javier Jiménez" <
reply@reply.github.com

**Comment by db2277** [comment]
hi man
any news ? :(

2012/1/22 Dan B - LotemX d@lotemx.com

> Iphone 4 version 4 or something.  Not ios5.
> בתאריך 2012 1 22 11:50, מאת "Javier Jiménez" <
> reply@reply.github.com
> 
> > :
> 
> What versin of mobile?
> 
> > El 22/01/2012 09:17, "db2277" <
> > reply@reply.github.com>
> > escribi:
> > 
> > > Hi Javier
> > > thanks for the reply.
> > > I really like the concept of LungoJS since its lightweight and cool
> > > (and i
> > > tried ALL frameworks).
> > > I changed to the order you wrote, but still same issue:
> > > Look: http://rvmon.lotemx.net/lungojs/index.html
> > > Thanks man
> > > Dan
> > > 
> > > 2012/1/22 Javier Jimnez <
> > > reply@reply.github.com
> > > 
> > > > The order in a section is
> > > > 
> > > > <section>
> > > >   <header>...
> > > >   <footer>...
> > > >   <aside>...
> > > > 
> > > >   <article>...
> > > >   <article>...
> > > > </section>
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3601739
> > > 
> > > ## 
> > > 
> > > Best regards,
> > > 
> > > _Dan Berachowitz, CEO_
> > > Lotem Group ltd.
> > > 
> > > Office: +972 (77) 8866789
> > > Mobile: +972 (52) 2269978
> > > 
> > > Hebrew: www.lotemx.com
> > > English: www.lotemx.net
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3601779
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3602052

## 

Best regards,

_Dan Berachowitz, CEO_
Lotem Group ltd.

Office: +972 (77) 8866789
Mobile: +972 (52) 2269978

Hebrew: www.lotemx.com
English: www.lotemx.net

**Comment by soyjavi** [comment]
I'm checking your settings ...

**Comment by db2277** [comment]
Thanks
:-)
בתאריך 2012 1 23 09:26, מאת "Javier Jiménez" <
reply@reply.github.com

**Comment by soyjavi** [comment]
Fixed!! Next friday I build release 1.1.1

https://github.com/TapQuo/Lungo.js/commit/57d2d4b23291720f310cce60a3bab8688f26c54d

**Comment by db2277** [comment]
cool! thanks.
i have another question (that im sure everyone would like to know):
how do i make tab-bar with pic and title like here:
http://lovedsgn.com/images/post/4980_7376dc13ab97d5edd69ee14e7e90a690dec6bce1.png

thanks
dan

2012/1/23 Javier Jimnez <
reply@reply.github.com

> Fixed!! Next friday I build release 1.1.1
> 
> https://github.com/TapQuo/Lungo.js/commit/57d2d4b23291720f310cce60a3bab8688f26c54d
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3611404

## 

Best regards,

_Dan Berachowitz, CEO_
Lotem Group ltd.

Office: +972 (77) 8866789
Mobile: +972 (52) 2269978

Hebrew: www.lotemx.com
English: www.lotemx.net

**Comment by db2277** [comment]
the problem still occurs.
i feel that the problem is with the header.
when i click on the tab-bar icons, the header disappear and then the tabbar
changes its position (and then the ugly space beneath them appear).

2012/1/23 Javier Jimnez <
reply@reply.github.com

> What problem?
> 
> 2012/1/23 db2277 <
> reply@reply.github.com
> 
> > im afraid the problem still exists.
> > http://rvmon.lotemx.net/lungojs/index.html
> > even in chrome it happens..
> > 
> > 2012/1/23 Dan B - LotemX d@lotemx.com
> > 
> > > cool! thanks.
> > > i have another question (that im sure everyone would like to know):
> > > how do i make tab-bar with pic and title like here:
> > 
> > http://lovedsgn.com/images/post/4980_7376dc13ab97d5edd69ee14e7e90a690dec6bce1.png
> > 
> > >  thanks
> > > dan
> > > 
> > > 2012/1/23 Javier Jimnez <
> > > reply@reply.github.com
> > > 
> > > > Fixed!! Next friday I build release 1.1.1
> > 
> > https://github.com/TapQuo/Lungo.js/commit/57d2d4b23291720f310cce60a3bab8688f26c54d
> > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3611404
> > > 
> > > ## 
> > > 
> > > Best regards,
> > > 
> > > _Dan Berachowitz, CEO_
> > > Lotem Group ltd.
> > > 
> > > Office: +972 (77) 8866789
> > > Mobile: +972 (52) 2269978
> > > 
> > > Hebrew: www.lotemx.com
> > > English: www.lotemx.net
> > 
> > ## 
> > 
> > Best regards,
> > 
> > _Dan Berachowitz, CEO_
> > Lotem Group ltd.
> > 
> > Office: +972 (77) 8866789
> > Mobile: +972 (52) 2269978
> > 
> > Hebrew: www.lotemx.com
> > English: www.lotemx.net
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3619339
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3620360

## 

Best regards,

_Dan Berachowitz, CEO_
Lotem Group ltd.

Office: +972 (77) 8866789
Mobile: +972 (52) 2269978

Hebrew: www.lotemx.com
English: www.lotemx.net

**Comment by soyjavi** [comment]
Still not released the 1.1.1 release:)

I've tested in a 4 and iPhone 3G iPhone and it workscorrectly.

2012/1/24 db2277 <
reply@reply.github.com

**Comment by db2277** [comment]
ahh ok :)
do you have solutions for galleries, carousels,tab-bars with titles, and
cool transitions between articles/sections?

2012/1/24 Javier Jimnez <
reply@reply.github.com

> Still not released the 1.1.1 release:)
> 
> I've tested in a 4 and iPhone 3G iPhone and it workscorrectly.
> 
> 2012/1/24 db2277 <
> reply@reply.github.com
> 
> > the problem still occurs.
> > i feel that the problem is with the header.
> > when i click on the tab-bar icons, the header disappear and then the
> > tabbar
> > changes its position (and then the ugly space beneath them appear).
> > 
> > 2012/1/23 Javier Jimnez <
> > reply@reply.github.com
> > 
> > > What problem?
> > > 
> > > 2012/1/23 db2277 <
> > > reply@reply.github.com
> > > 
> > > > im afraid the problem still exists.
> > > > http://rvmon.lotemx.net/lungojs/index.html
> > > > even in chrome it happens..
> > > > 
> > > > 2012/1/23 Dan B - LotemX d@lotemx.com
> > > > 
> > > > > cool! thanks.
> > > > > i have another question (that im sure everyone would like to know):
> > > > > how do i make tab-bar with pic and title like here:
> > 
> > http://lovedsgn.com/images/post/4980_7376dc13ab97d5edd69ee14e7e90a690dec6bce1.png
> > 
> > > > >  thanks
> > > > > dan
> > > > > 
> > > > > 2012/1/23 Javier Jimnez <
> > > > > reply@reply.github.com
> > > > > 
> > > > > > Fixed!! Next friday I build release 1.1.1
> > 
> > https://github.com/TapQuo/Lungo.js/commit/57d2d4b23291720f310cce60a3bab8688f26c54d
> > 
> > > > > > ---
> > > > > > 
> > > > > > Reply to this email directly or view it on GitHub:
> > > > > > https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3611404
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Best regards,
> > > > > 
> > > > > _Dan Berachowitz, CEO_
> > > > > Lotem Group ltd.
> > > > > 
> > > > > Office: +972 (77) 8866789
> > > > > Mobile: +972 (52) 2269978
> > > > > 
> > > > > Hebrew: www.lotemx.com
> > > > > English: www.lotemx.net
> > > > 
> > > > ## 
> > > > 
> > > > Best regards,
> > > > 
> > > > _Dan Berachowitz, CEO_
> > > > Lotem Group ltd.
> > > > 
> > > > Office: +972 (77) 8866789
> > > > Mobile: +972 (52) 2269978
> > > > 
> > > > Hebrew: www.lotemx.com
> > > > English: www.lotemx.net
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3619339
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3620360
> > 
> > ## 
> > 
> > Best regards,
> > 
> > _Dan Berachowitz, CEO_
> > Lotem Group ltd.
> > 
> > Office: +972 (77) 8866789
> > Mobile: +972 (52) 2269978
> > 
> > Hebrew: www.lotemx.com
> > English: www.lotemx.net
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3628494
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TapQuo/Lungo.js/issues/58#issuecomment-3628771

## 

Best regards,

_Dan Berachowitz, CEO_
Lotem Group ltd.

Office: +972 (77) 8866789
Mobile: +972 (52) 2269978

Hebrew: www.lotemx.com
English: www.lotemx.net
